---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 459de79ebc6a72a586d30f83d9221c6878ab4664
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: test-customer-interface
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=i-disa-test-customer-interface&var-version=0.1.0
  labels:
    app: i-disa-test-customer-interface
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-disa-test-customer-interface
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: i-disa-test-customer-interface
      provider: fabric8
      group: com.redhat
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 459de79ebc6a72a586d30f83d9221c6878ab4664
        fabric8.io/iconUrl: img/icons/camel.svg
        fabric8.io/git-branch: test-customer-interface
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=i-disa-test-customer-interface&var-version=0.1.0
      labels:
        app: i-disa-test-customer-interface
        provider: fabric8
        version: 0.1.0
        group: com.redhat
    spec:
      containers:
      - env:
        - name: SPRING_APPLICATION_JSON
          value: '{"server":{"tomcat":{"max-threads":1}}}'
        - name: JAVA_APP_JAR
          value: i-disa-test-customer-interface-0.1.0.jar
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: i-disa-test-customer-interface:0.1.0
        imagePullPolicy: IfNotPresent
        name: i-disa-test-customer-interface
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: sunproxyadmin
          protocol: TCP
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
