---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 733938cab102aa76246bdb327cd32b5a0964113a
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: proveedor
  labels:
    expose: "true"
    app: i-disaprd-supplier
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-disaprd-supplier
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-disaprd-supplier
    provider: fabric8
    group: com.redhat
